apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-deploy
    labels:
      app: app
spec:
    replicas: 3
    selector:
        matchLabels:
            app: app
    template:
        metadata:
            labels:
                app: app
        spec:
            containers:
            - name: richarddevops
              image: richarddevops/app-helm:latest
              command: [ "echo", "SUCCESS" ]
              ports:
                - containerPort: 3000
                          imagePullSecrets:
            - name: regcred
